all:
	gcc A_saucebowls.c -o saucebowl
	gcc A_Semaphore.c -o semaphore
	gcc A_StrictOrdering.c -o strictordering
	gcc A_bowl_strict_ordering.c -o saucebowlordering
	
clean:
	rm saucebowl semaphore strictordering saucebowlordering
